name:                foreign-store-stm
version:             0.1.0.1

dependencies:
- base >= 4.7 && < 5
- foreign-store
- stm

default-extensions:
- OverloadedStrings
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- BlockArguments
- RankNTypes
- MultiParamTypeClasses
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  tstore-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - foreign-store-stm
