name:                live-store
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
# - ghc-hotswap
- containers
#- stm
- foreign-store

default-extensions:
- OverloadedStrings
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- BlockArguments
- RankNTypes
- MultiParamTypeClasses
- TypeApplications

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  live-store-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - live-store
